name: eid-card
region: fra
static_sites:
  - name: eid-card
    github:
      repo: mesharibashiri/Gift-Card
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    catchall_document: index.html
